INSERT INTO onboarding_items (section_id, item_type, form_id, work_document_id, sort_order) VALUES
  ((SELECT id FROM onboarding_sections WHERE program_id = (SELECT id FROM onboarding_programs WHERE title = 'New Assistant Manager Onboarding') AND title = 'Required forms to complete'), 'policy_signoff', NULL, (SELECT id FROM work_documents WHERE title = 'Welcome Letter - Assistant Manager (needs editing in source)'), 0),
  ((SELECT id FROM onboarding_sections WHERE program_id = (SELECT id FROM onboarding_programs WHERE title = 'New Assistant Manager Onboarding') AND title = 'Required forms to complete'), 'form', (SELECT id FROM forms WHERE title = 'Update Personal Details Form'), NULL, 1),
  ((SELECT id FROM onboarding_sections WHERE program_id = (SELECT id FROM onboarding_programs WHERE title = 'New Assistant Manager Onboarding') AND title = 'Required forms to complete'), 'form', (SELECT id FROM forms WHERE title = 'Ted''s Cameras Employee Banking Details Form'), NULL, 2),
  ((SELECT id FROM onboarding_sections WHERE program_id = (SELECT id FROM onboarding_programs WHERE title = 'New Assistant Manager Onboarding') AND title = 'Required forms to complete'), 'policy_signoff', NULL, (SELECT id FROM work_documents WHERE title = 'Superannuation Choice Form'), 3),
  ((SELECT id FROM onboarding_sections WHERE program_id = (SELECT id FROM onboarding_programs WHERE title = 'New Assistant Manager Onboarding') AND title = 'Required forms to complete'), 'form', (SELECT id FROM forms WHERE title = 'Tax Declaration Form'), NULL, 4),
  ((SELECT id FROM onboarding_sections WHERE program_id = (SELECT id FROM onboarding_programs WHERE title = 'New Assistant Manager Onboarding') AND title = 'Ted''s Cameras Code of Conduct'), 'policy_signoff', NULL, (SELECT id FROM work_documents WHERE title = 'Code of Conduct Letter'), 0),
  ((SELECT id FROM onboarding_sections WHERE program_id = (SELECT id FROM onboarding_programs WHERE title = 'New Assistant Manager Onboarding') AND title = 'Ted''s Cameras Code of Conduct'), 'policy_signoff', NULL, (SELECT id FROM work_documents WHERE title = 'Code of Conduct Ted''s Cameras'), 1),
  ((SELECT id FROM onboarding_sections WHERE program_id = (SELECT id FROM onboarding_programs WHERE title = 'New Assistant Manager Onboarding') AND title = 'Ted''s Cameras Code of Conduct'), 'form', (SELECT id FROM forms WHERE title = 'Code of Conduct Signature'), NULL, 2),
  ((SELECT id FROM onboarding_sections WHERE program_id = (SELECT id FROM onboarding_programs WHERE title = 'New Assistant Manager Onboarding') AND title = 'Required Reading'), 'policy_signoff', NULL, (SELECT id FROM work_documents WHERE title = 'Rest Super Product Disclosure Statement'), 0),
  ((SELECT id FROM onboarding_sections WHERE program_id = (SELECT id FROM onboarding_programs WHERE title = 'New Assistant Manager Onboarding') AND title = 'Required Reading'), 'policy_signoff', NULL, (SELECT id FROM work_documents WHERE title = 'Fair Work Information Statement'), 1),
  ((SELECT id FROM onboarding_sections WHERE program_id = (SELECT id FROM onboarding_programs WHERE title = 'New Assistant Manager Onboarding') AND title = 'Required Reading'), 'policy_signoff', NULL, (SELECT id FROM work_documents WHERE title = 'Ted''s Emplive and ADP New Starter Info'), 2),
  ((SELECT id FROM onboarding_sections WHERE program_id = (SELECT id FROM onboarding_programs WHERE title = 'New Assistant Manager Onboarding') AND title = 'Required Reading'), 'policy_signoff', NULL, (SELECT id FROM work_documents WHERE title = 'Dress Code Policy - Ted’s Cameras and Digital Camera Warehouse'), 3),
  ((SELECT id FROM onboarding_sections WHERE program_id = (SELECT id FROM onboarding_programs WHERE title = 'New Assistant Manager Onboarding') AND title = 'Required Reading'), 'policy_signoff', NULL, (SELECT id FROM work_documents WHERE title = 'Staff Purchasing Policy - Ted’s Cameras and Digital Camera Warehouse'), 4);
